Tests run  7
Errors  []
[(<LexerSuite.LexerSuite testMethod=test_illegal_escape>,
  'Traceback (most recent call last):\n'
  '  File "./test/LexerSuite.py", line 22, in test_illegal_escape\n'
  '    self.assertTrue(TestLexer.checkLexeme(""" "abc\\\\h def"  '
  '""","""Illegal Escape In String: abc\\\\h""",105))\n'
  'AssertionError: False is not true\n'),
 (<LexerSuite.LexerSuite testMethod=test_normal_string_with_escape>,
  'Traceback (most recent call last):\n'
  '  File "./test/LexerSuite.py", line 30, in test_normal_string_with_escape\n'
  '    self.assertTrue(TestLexer.checkLexeme(""" "ab\'"c\\\\n def"  '
  '""","""ab\'"c\\\\n def,<EOF>""",107))\n'
  'AssertionError: False is not true\n'),
 (<LexerSuite.LexerSuite testMethod=test_unterminated_string>,
  'Traceback (most recent call last):\n'
  '  File "./test/LexerSuite.py", line 26, in test_unterminated_string\n'
  '    self.assertTrue(TestLexer.checkLexeme(""" "abc def  ""","""Unclosed '
  'String: abc def  """,106))\n'
  'AssertionError: False is not true\n')]
Test output
 F...FF.
======================================================================
FAIL: test_illegal_escape (LexerSuite.LexerSuite)
test illegal escape
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/LexerSuite.py", line 22, in test_illegal_escape
    self.assertTrue(TestLexer.checkLexeme(""" "abc\\h def"  ""","""Illegal Escape In String: abc\\h""",105))
AssertionError: False is not true

======================================================================
FAIL: test_normal_string_with_escape (LexerSuite.LexerSuite)
test normal string with escape
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/LexerSuite.py", line 30, in test_normal_string_with_escape
    self.assertTrue(TestLexer.checkLexeme(""" "ab'"c\\n def"  ""","""ab'"c\\n def,<EOF>""",107))
AssertionError: False is not true

======================================================================
FAIL: test_unterminated_string (LexerSuite.LexerSuite)
test unclosed string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/LexerSuite.py", line 26, in test_unterminated_string
    self.assertTrue(TestLexer.checkLexeme(""" "abc def  ""","""Unclosed String: abc def  """,106))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.005s

FAILED (failures=3)

